version: '3.3'

services:
  db:
    container_name: FoodDb
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    container_name: backend_foodgram
    build: ../backend/
    restart: always
    volumes:
      - static_food:/app/static/
      - media_food:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    container_name: frontend_foodgram
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-nginx
    image: nginx:1.22.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_food:/var/html/static/
      - media_food:/var/html/media/
    depends_on:
      - backend

volumes:
  static_food:
  media_food:
  db_data: