version: '3.9'

volumes:
  static_food:
  media_food:
  db_data:

services:

  db:
    image: postgres:13.3-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  backend:
    image: stefa2003/backend_foodgram:latest
    restart: always
    volumes:
      - static_food:/app/static/
      - media_food:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: stefa2003/frontend_foodgram:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_food:/var/html/static/
      - media_food:/var/html/media/
    depends_on:
      - backend
      - frontend
